capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shiftswap/', include('shiftswap.urls')),
]

capstone/shiftswap/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'shiftswap'
urlpatterns = [
  path('index/', views.index, name='index'),
  path('register/', views.register, name='register'),
  path('post/', views.post, name='post'),
  path('login_user/', views.login_user, name='login_user'),
  path('apply/', views.apply, name='apply'),
  path('apply/<int:id>', views.apply, name='apply'),
  path('info/', views.info, name='info'),
  path('logout_user/', views.logout_user, name='logout'),
  path('profile/', views.profile, name='profile'),
  path('applyjob/<int:id>', views.applyjob, name='applyjob'),
  path('postjob/', views.postjob, name='postjob'),
  path('edit/<int:id>', views.edit, name='edit'),
  path('edit/', views.edit, name='edit'),
  path('helloworld/', views.hello, name='hello'),
]

capstone/shiftswap/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_contractor = models.BooleanField(default=False)
    is_employer = models.BooleanField(default=False)
    company = models.CharField(max_length=200)
    company_location = models.CharField(max_length=150)

    def __str__(self):
        return self.username


class JobCard(models.Model):
    type = models.CharField(max_length=200)
    employer = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user_company')
    description = models.CharField(max_length=400, blank=True)
    date = models.DateField(null=True, blank=True, default=None)
    start_time = models.TimeField(default=None)
    end_time = models.TimeField(default=None)
    pay = models.FloatField(default=0.00)
    review = models.CharField(max_length=400, blank=True)
    applied = models.ManyToManyField(User, related_name='applied')

    def __str__(self):
        return self.type

capstone/shiftswap/forms.py
# shiftswap/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User

class UserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'is_contractor', 'is_employer', 'company', 'company_location')

class UserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = User
        fields = ('username', 'is_contractor', 'is_employer', 'company', 'company_location')

capstone/shiftswap/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import User, JobCard
from datetime import date, datetime, timedelta
import json


def index(request):
    data = JobCard.objects.order_by('-date')
    user = User.objects.all()
    job_list = JobCard.objects.get_queryset().order_by('-date')
    page = request.GET.get('page', 1)

    paginator = Paginator(job_list, 8)
    try:
        jobs = paginator.page(page)
    except PageNotAnInteger:
        jobs = paginator.page(1)
    except EmptyPage:
        jobs = paginator.page(paginator.num_pages)
    # opening json data file
    ## loaded a mock json with data info, parsed and then save to database
    # with open('Capstone/capstone/shiftswap/MOCK_DATA.json') as f:
    #     data = json.load(f)
    # for x in data:
    #     company = x['company']
    #     type = x['type']
    #     date = x['date']
    #     start_time = x['start_time']
    #     end_time = x['end_time']
    #     pay = x['pay']
    #     logo = x['logo']
    #     post = JobCard(employer=User(id=3,company=company), type=type, date=date, start_time=start_time, end_time=end_time, pay=pay, description=logo)
    #     post.save()
    context = {
    'data': data,
    'user': user,
    'jobs': jobs,
    }
    return render(request, 'shiftswap/index.html', context)

def register(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    is_employer = request.POST['inlineRadioOptions']
    is_contractor = request.POST['inlineRadioOptions']
    if request.POST['inlineRadioOptions'] == 'is_employer':
        user = User.objects.create_user(username=username, email=email, password=password, is_staff=True, is_employer=True) #is_employer or is_contractor=True
        user.save()
    else:
        user = User.objects.create_user(username=username, email=email, password=password, is_staff=True, is_contractor=True)
        user.save()
    login(request, user)
    # User.objects.create_user(username, email, password)
    return HttpResponseRedirect(reverse('shiftswap:index'))


def info(request):
    jobs = JobCard.objects.all()
    context = {
    'jobs': jobs,
    }
    return render(request, 'shiftswap/jobinfo.html', context)

def login_user(request):
    if request.method == 'GET':
        return render(request, 'shiftswap/login.html')
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    # print(request.POST)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('shiftswap:index'))
    else:
        return HttpResponseRedirect(reverse('shiftswap:login_user'))


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('shiftswap:index'))

def postjob(request):
    print(request.POST)
    jobs = JobCard.objects.all()
    type = request.POST['type']
    pay = request.POST['pay']
    date = request.POST['date']
    start_time = request.POST['start_time']
    end_time = request.POST['end_time']
    postingjob = JobCard.objects.create(type=type, employer=request.user, pay=pay, date=date, start_time=start_time, end_time=end_time)
    return HttpResponseRedirect(reverse('shiftswap:index'))


@login_required
def post(request):
    if request.user.is_employer or request.user.is_superuser:
        current_user = request.user
        context = {
        }
        return render(request, 'shiftswap/post.html', context)
    else:
        return HttpResponseRedirect(reverse('shiftswap:index'))

@login_required
def applyjob(request, id):
    if request.method == 'GET':
        user = request.user.id
        job = JobCard.objects.get(id=id)
        job.applied.add(request.user)
        # in jobinfo page, when click apply, sends request through applyjob views with jobid, if request.method is get, pull id out
        # testing prints
        # print('>>>>')
        # print(job.id)
        # print(request.user.id)
    return HttpResponseRedirect(reverse('shiftswap:index'))

@login_required
def apply(request, id):
    if request.user.is_authenticated:
        if request.method == 'GET':
            job = JobCard.objects.get(id=id)
            user = User.objects.all()
            now = datetime.now()
            dt = datetime.combine(job.date, datetime.min.time())
            job_posted_date = dt - now
            context = {
            'job': job,
            'job_posted_date': job_posted_date,
            'user': user,
            }
        return render(request, 'shiftswap/jobinfo.html', context)
    else:
        return HttpResponseRedirect(reverse('shiftswap:login_user'))

@login_required
def edit(request, id):
    if request.user.is_authenticated:
        editjob = JobCard.objects.get(id=id)
        context = {
        'editjob': editjob,
        }
        return render(request, 'shiftswap/edit.html', context)
    else:
        return HttpResponseRedirect(reverse('shiftswap:login_user'))


@login_required
def profile(request):
    if request.user.is_authenticated:
        current_user = request.user
        # searches for all jobs applied for by requested user.
        postedjobs = JobCard.objects.filter(employer=request.user)
        lookingup = JobCard.objects.filter(applied=request.user)
        # print('>>>>>>>>>>>>>')
        # print(current_user.__dict__)
        # print(current_user.username)
        # print(current_user.email)
        # print(current_user.id)
        context = {
        'postedjobs': postedjobs,
        'lookingup': lookingup,
        }
        return render(request, 'shiftswap/profile.html', context)
    else:
        return HttpResponseRedirect(reverse('shiftswap:index'))

@login_required
def hello(request):
    if request.user.is_superuser:
        return render(request, 'shiftswap/hello.html')
    else:
        return HttpResponseRedirect(reverse('shiftswap:index'))

capstone/shiftswap/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <title>SHIFTswap</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://cdn.lineicons.com/2.0/LineIcons.css" rel="stylesheet">
</head>
<style type="text/css">
  .container-main {
    padding-top: 100px;
    padding-bottom: 60px;
    margin: 0 auto;
  }

  .box {
    display: flex;
    flex-wrap: wrap;
    width: 100%;
    flex-direction: row;
    padding: 20px;
    margin: 0 auto;
  }

  .card {
    width: 25%;
    text-align: left;
  }

  .card-footer {
    text-align: right;
  }

  footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    height: 2.9rem;
    color: white;
    text-align: center;
  }
</style>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <img src="{% static 'shiftswap/logo1.png' %}" height="50" width="150"></img>
    <div class="container">
      <a class="navbar-brand" href="#">{{request.user}}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'shiftswap:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>

          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'shiftswap:profile' %}">Profile</a>
            {% else %}
            <a class="nav-link" href="{% url 'shiftswap:apply' %}">Profile</a>
            {% endif %}
          </li>

          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'shiftswap:logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'shiftswap:login_user' %}">Login</a>
            {% endif %}
          </li>

          <li class="nav-item">
            <!-- Button trigger modal -->
            {% if request.user.is_authenticated %}
            {% else %}
            <button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#exampleModal">
              Register
            </button>
            {% endif %}
          </li>


        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Register</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="{% url 'shiftswap:register' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" placeholder="Username" name="username">
                <input type="email" name="email" placeholder="Email">
              </div>
              <div class="form-group">
                <input type="password" name="password" placeholder="Password">

                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="is_contractor" checked>
                  <label class="form-check-label" for="inlineRadio1">Contractor</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="is_employer">
                  <label class="form-check-label" for="inlineRadio2">Employer</label>
                </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Register</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="container-main">


      <!-- Page Features -->
      {% block content %}

      {% endblock %}

      <!-- /.row -->

    </div>

    <!-- /.container -->

    <!-- Footer -->
    <footer class="footer fixed-bottom navbar-dark bg-dark">
      <div class="container">
        <p>
          <a href="http://www.facebook.com"><img src="https://img.icons8.com/color/48/000000/facebook-new.png" /></a>
          <a href="http://www.instagram.com"><img src="https://img.icons8.com/color/48/000000/instagram-new.png" /></a>
          <a href="http://www.twitter.com"><img src="https://img.icons8.com/color/48/000000/twitter.png" /></a>
          {% if request.user.is_superuser %}
          <a href="{% url 'shiftswap:hello' %}"><img src="https://img.icons8.com/doodle/48/000000/plus--v1.png"/></a>
          {% endif %}
        </p>

      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>

capstone/shiftswap/templates/shiftswap/apply.html
{% extends 'base.html' %}
{% block content %}





{% endblock %}

capstone/shiftswap/templates/shiftswap/edit.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <form action="{% url 'shiftswap:edit' editjob.id %}" method="POST">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="type">Job Type</label>
        <input type="type" name="type" class="form-control" id="type" placeholder="{{editjob.type}}" required />
      </div>
      <div class="form-group col-md-4">
        <label for="pay">Pay</label>
        <input type="pay" name="pay" class="form-control" id="pay" placeholder="{{editjob.pay}}" required />
      </div>
      <div class="form-group col-md-4">
        <label for="location">Location</label>
        <input type="location" name="location" class="form-control" id="location" placeholder="{{editjob.employer.company_location}}" required />
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="example-date-input">Date</label>
        <input class="form-control" name="date" type="date" id="date" required />
      </div>
      <div class="form-group col-md-4">
        <label for="start_time">Start Time</label>
        <input type="time" name="start_time" class="form-control" id="start_time" required />
      </div>
      <div class="form-group col-md-4">
        <label for="end_time">End Time</label>
        <input type="time" name="end_time" class="form-control" id="end_time" required />
      </div>
    </div>
    <div class="form-row float-right">

      <a href="{% url 'shiftswap:profile' %}" class="btn btn-primary btn-sm">Cancel</a>
      <span>&nbsp;</span>
      <button type="submit" class="btn btn-primary btn-sm">Post Job</button>

    </div>
  </form>
</div>

{% endblock %}

capstone/shiftswap/templates/shiftswap/index.html
{% extends 'base.html' %}
{% block content %}

<!-- Page Features -->

<div class="text-center">
  <div class="box">
    {% for job in jobs %}
    <div class="card h-100">
      <img class="card-img-top" src="https://picsum.photos/200/300?random={{job.pay}}" width="130" height="130" alt="">
      <div class="card-body">
        <h4 class="card-title">{{job.type}}</h4>
        <p class="card-text">
          <!-- job.employer.company pulling info from JobCard employer field, to foriegnkey of User of employer/company field -->
          Business: {{job.employer.company}}<br />
          Date: {{job.date}}<br />
          From: {{job.start_time}} to {{job.end_time}}<br />
          Pay: ${{job.pay}}<br />
          ID: {{job.id}}
        </p>
      </div>
      <div class="card-footer">
        <a href="{% url 'shiftswap:apply' job.id %}" type="button" class="btn btn-info btn-secondary btn-sm">Apply</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<div class="d-flex justify-content-center">

</div>


<nav aria-label="Page navigation example">

</nav>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if jobs.has_other_pages %}
    {% if jobs.has_previous %}
    <li class="page-link" href="#" tabindex="-1"><a class="page-item disabled" href="?page={{ jobs.previous_page_number }}">Previous</a></li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">Previous</span></li>
    {% endif %}
    {% for i in jobs.paginator.page_range %}
    {% if jobs.number == i %}
    <li class="page-item active">
      <span class="page-link">{{i}}
        <span class="sr-only">(current)</span>
      </span></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if jobs.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ jobs.next_page_number }}">Next</a></li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
    {% endif %}
  </ul>
</nav>

{% endblock %}

capstone/shiftswap/templates/shiftswap/jobinfo.html
{% extends 'base.html' %}
{% block content %}



<div class="card border-dark w-100 text-center">
  <div class="card-header">
    JOB POSTING ID: {{job.id}}
  </div>
  <div class="card-body">

    <h5 class="card-title">{{job.type}}</h5>
    <p class="card-text text-left">
      Business: {{job.employer.company}}<br />
      Job Type: {{job.type}}<br />
      Date: {{job.date}}<br />
      From: {{job.start_time}} to {{job.end_time}}<br />
      Pay: ${{job.pay}}<br />
      ID: {{job.id}}<br /><br />
      <b>WHO APPLIED:</b> <br>
      {% for who in job.applied.all %}
      {{ who }}<br />
      {% endfor %}
    </p>
    {{page}}
    <a href="{% url 'shiftswap:index' %}" class="btn btn-primary btn-sm">Cancel</a>
    <a href="{% url 'shiftswap:applyjob' job.id %}" class="btn btn-primary btn-sm">Apply</a>
  </div>
  <div class="card-footer text-muted">
    Starts: {{job_posted_date}}
  </div>
</div>


{% endblock %}

capstone/shiftswap/templates/shiftswap/logout.html
<!DOCTYPE html>
<html lang="" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>SHIFTswap</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Register
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Register</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{% url 'shiftswap:register' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" placeholder="Username" name="username">
              <input type="email" name="email">
            </div>
            <div class="form-group">
              <input type="password" name="password">
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>



  <h1>{{message}}</h1>

  {% for job in jobs %}
  Job: {{job.type}}<br />
  Company: {{job.employer}}<br />
  Date: {{job.start_date}} to {{job.end_date}} <br />
  Pay: {{job.pay}}<br />
  {% endfor %}


  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

capstone/shiftswap/templates/shiftswap/post.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <form action="{% url 'shiftswap:postjob' %}" method="POST">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="type">Job Type</label>
        <input type="type" name="type" class="form-control" id="type" required>
      </div>
      <div class="form-group col-md-4">
        <label for="pay">Pay</label>
        <input type="pay" name="pay" class="form-control" id="pay" required>
      </div>
      <div class="form-group col-md-4">
        <label for="location">Location</label>
        <input type="pay" name="location" class="form-control" id="pay" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="example-date-input">Date</label>
        <input class="form-control" name="date" type="date" id="date" required>
      </div>
      <div class="form-group col-md-4">
        <label for="start_time">Start Time</label>
        <input type="time" value="06:45:00" name="start_time" class="form-control" id="start_time" required>
      </div>
      <div class="form-group col-md-4">
        <label for="end_time">End Time</label>
        <input type="time" value="09:45:00" name="end_time" class="form-control" id="end_time" required>
      </div>
    </div>
    <div class="form-row float-right">

      <a href="{% url 'shiftswap:index' %}" class="btn btn-primary btn-sm">Cancel</a>
      <span>&nbsp;</span>
      <button type="submit" class="btn btn-primary btn-sm">Post Job</button>

    </div>
  </form>
</div>

{% endblock %}

capstone/shiftswap/templates/shiftswap/profile.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <h5><span>PROFILE PAGE</span><span style="float:right">
      {% if request.user.is_employer or request.user.is_superuser%}
      <a href="{% url 'shiftswap:post' %}" alt="Post Job">
        <img src="https://img.icons8.com/windows/48/000000/add-property.png" /></a>
      {% else %}
      <img src="https://img.icons8.com/windows/48/000000/add-property.png" />
      {% endif %}
    </span></h5>
  <br />
  <div class="row">
    <div class="col-sm-5">
      <p>
        <strong>USER:</strong> <br /><br />
        Name: {{user.get_username}}<br />
        Email: {{user.email}}<br />

      </p>
    </div>

    <div class="col-sm-4">
      <ul style="list-style-type:none">
        <strong>REVIEW COLUMN:</strong> <br /><br />
        <li></li>
      </ul>
    </div>

    <div class="col-sm-3">
      <ul style="list-style-type:none">
        {% if request.user.is_superuser or request.user.is_employer %}
        <strong>POSTED JOBS:</strong><br /><br />
        {% for pjob in postedjobs %}
        <li><span><a href="{% url 'shiftswap:edit' pjob.id %}"><img src="https://img.icons8.com/officexs/26/000000/edit.png" /></a></span>
          <span>{{pjob}}</span></li>
        {% endfor %}
        <br /><br />
        <strong>APPLIED JOBS:</strong><br /><br />
        {% for info in lookingup %}
        <li>{{info}} ({{info.id}})
        </li>
        {% endfor %}
        {% else %}
        <strong>APPLIED JOBS:</strong><br /><br />
        {% for info in lookingup %}
        <li>{{info}} ({{info.id}})
        </li>
        {% endfor %}
        {% endif %}

      </ul>
    </div>


  </div>
</div>





{% endblock %}